# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master 
 
stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Gradle@2
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'build'
    
    - task: AzureWebApp@1
      inputs:
        azureSubscription: poc_test_connection
        appType: webAppLinux
        appName: cedrus-poc-spring2
        package: '$(System.DefaultWorkingDirectory)/build/libs/*.jar'
   
# - stage: Deploy
#   displayName: Deploy stage
#   dependsOn: Build
#   jobs:
#   - deployment: VMDeploy
#     displayName: web
#     environment:
#       name:  spring-app-deployment
#       resourceType: VirtualMachine
#       tags: poc

# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

# name: Azure App Service - cedrus-poc-spring(Production), Build and deploy Spring app

# # on:
# #   push:
# #     branches:
# #       - master


# trigger:
# - master 

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     # checkout the repo
#     - name: 'Checkout Github Action'
#       uses: actions/checkout@master


#     - name: Set up Java version
#       uses: actions/setup-java@v1
#       with:
#         java-version: '11'

#     - name: Build with Gradle
#       run: ./gradlew build

#     - name: Run Azure webapp deploy action using publish profile credentials
#       uses: azure/webapps-deploy@v2
#       with:
#         app-name: cedrus-poc-spring
#         slot-name: Production
#         publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2298599E4BE1429088B5A0022D338CFA }}
#         package: ${{ github.workspace }}/build/libs/*.jar
